### ISSUE TITLE
Install VLC 3.0+

### ISSUE THREAD

**Issue by BryanArnold** [NateMccomb/TeslaCamViewerII#10]
I have 2019.46.6.1 installed, and also installed VLC 3.0.8.

When I launch TeslaCamViewerII I get the message popup to install VLC, even though it's installed. Tried rebooting, uninstalling and reinstalling with no success.

I am also unable to switch to VLC in the preferences. VLC was installed with the required checkboxes checked.

Any ideas? Thanks!

**Comment by NateMccomb** [comment]
When installing VLC make sure that "Web Plugins" & "ActiveX Plugin" are both checked as optional components you wish to install. Still working on figuring out whether the 32bit and/or 64bit version both work.

**Comment by BryanArnold** [comment]
Thanks for the reply and your time. I did make sure those were checked on both installs tries. What bit version should I install?

**Comment by BryanArnold** [comment]
Update... I had the 64 bit VLC installed, tried the 32 bit version. Uninstalled and reinstalled, made sure the Web Plugins" & ActiveX Plugins were checked. No change, still does not see it.

**Comment by ryderdonahue** [comment]
I have the same issue reproducing

**Comment by gaardiolor** [comment]
I have the same issue.

**Comment by gaardiolor** [comment]
Apparently the app is checking if VLC is installed by checking registry key `HKLM\SOFTWARE\VideoLAN\VLC`, which doesn't exist after installing VLC. Maybe it was used by an older version. After manually creatingn the key, VLC is available from the dropdown in settings.

But now, after selecting a SentryClips subdirectory, the app hangs.

**Comment by jbienz** [comment]
Unlike @gaardiolor, I DO have the registry key `HKLM\SOFTWARE\VideoLAN\VLC` after installing VLC.

However, like @gaardiolor I am seeing the same ActiveX errors in my log file. This happens right after selecting a folder.

```
11/26/2019 5:54:19.145 PM - Error - Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)) IN:CoCreateInstance
   at System.Windows.Forms.UnsafeNativeMethods.CoCreateInstance(Guid& clsid, Object punkOuter, Int32 context, Guid& iid)
   at System.Windows.Forms.AxHost.CreateWithLicense(String license, Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstanceCore(Guid clsid)
   at System.Windows.Forms.AxHost.CreateInstance()
   at System.Windows.Forms.AxHost.GetOcxCreate()
   at System.Windows.Forms.AxHost.TransitionUpTo(Int32 state)
   at System.Windows.Forms.AxHost.CreateHandle()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.ControlCollection.Add(Control value)
   at TeslaCam_Viewer.MainForm.PlayerExist(String PlayerName)
11/26/2019 5:54:19.239 PM - Error - Object reference not set to an instance of an object. IN:LoadTimesToCurrentTimeList
   at TeslaCam_Viewer.MainForm.LoadTimesToCurrentTimeList()
11/26/2019 5:54:19.248 PM - Error - Exception of type 'System.Windows.Forms.AxHost+InvalidActiveXStateException' was thrown. IN:get_input
   at AxAXVLC.AxVLCPlugin2.get_input()
```

Looks like the app is not successful at instantiating the VLC ActiveX control.

**Comment by NateMccomb** [comment]
Try 2019.52.0.0
I've updated where TCV checks in the registry to see if the VLC ActiveX plugins are installed. 
SOFTWARE\WOW6432Node\Classes\TypeLib\{DF2BBE39-40A8-433B-A279-073F48DA94B6}\1.0\0\win64
&
SOFTWARE\WOW6432Node\Classes\TypeLib\{DF2BBE39-40A8-433B-A279-073F48DA94B6}\1.0\0\win32

If TCV is running in 64bit mode then the 64bit version of VLC is needed otherwise the 32bit version of TCV will need the 32bit version of VLC. Code has been added to detect what version should be installed. Let me know if this clears up your issues you have been experiencing.

**Comment by BryanArnold** [comment]
The new version worked in detecting and using VLC, thanks so much!

**Comment by SiNaPsEr0x** [comment]
> Apparently the app is checking if VLC is installed by checking registry key `HKLM\SOFTWARE\VideoLAN\VLC`, which doesn't exist after installing VLC. Maybe it was used by an older version. After manually creating the key, VLC is available from the dropdown in settings.
> 
> But now, after selecting a SentryClips subdirectory, the app hangs. Logfile (these messages keep coming until you close TeslaCamViewer):
> 
> ```
> 23-Nov-19.307 23:34:32 - Error - Exception of type 'System.Windows.Forms.AxHost+InvalidActiveXStateException' was thrown. IN:get_input
>    at AxAXVLC.AxVLCPlugin2.get_input()
>    at TeslaCam_Viewer.MainForm.Timer1_Tick(Object sender, EventArgs e)
> 23-Nov-19.421 23:34:32 - Error - Exception of type 'System.Windows.Forms.AxHost+InvalidActiveXStateException' was thrown. IN:get_input
>    at AxAXVLC.AxVLCPlugin2.get_input()
>    at TeslaCam_Viewer.MainForm.Timer1_Tick(Object sender, EventArgs e)
> ```

some problem

**Comment by SiNaPsEr0x** [comment]
> Try 2019.52.0.0
> I've updated where TCV checks in the registry to see if the VLC ActiveX plugins are installed.
> SOFTWARE\WOW6432Node\Classes\TypeLib{DF2BBE39-40A8-433B-A279-073F48DA94B6}\1.0\0\win64
> &
> SOFTWARE\WOW6432Node\Classes\TypeLib{DF2BBE39-40A8-433B-A279-073F48DA94B6}\1.0\0\win32
> 
> If TCV is running in 64bit mode then the 64bit version of VLC is needed otherwise the 32bit version of TCV will need the 32bit version of VLC. Code has been added to detect what version should be installed. Let me know if this clears up your issues you have been experiencing.

worked for me... install 32bit
