### ISSUE TITLE
Feature request: Have a "Delete" item in the context menu of the explorer pane

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewerII#11]
An item "Delete" there could improve the workflow greatly.

Workflow now:
* View event
* It's not important
* Right click "open" -> Explorer
* Select another event in TeslaCamViewer
* Navigate in explorer one directory back
* Delete the whole directory

Proposed workflow:
* View event
* It's not important
* Right click "Delete" -> it's zapped

<img width="382" alt="context-menu" src="https://user-images.githubusercontent.com/12480900/69186227-70559900-0b18-11ea-8491-13fb9fda145f.png">

**Comment by NateMccomb** [comment]
I had this feature added a while back but thought it was causing other issues and disabled it, I have re-added it back to 2019.52.0.0

**Comment by Kumasasa** [comment]
Well, it works.
Kinda.
The folder is in fact delete, but the "Explorer"-Tree in TCV probably not updated and TCV crashes/hangs when trying to access the deleted folder.

**Comment by NateMccomb** [comment]
I think I got this working correctly now in 2019.52.1.0. If a folder is currently being viewed or the root nodes are selected then the Delete option will be disabled. Once a file or folder is Deleted then it will also be removed from the explorer windows preventing you from re-selecting it.

**Comment by Kumasasa** [comment]
Yes, thanks, it's working now perfectly!
