### ISSUE TITLE
Can't move In Point Marker and Out Point Marker with the mouse

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewerII#12]
Tooltip is shown, but it cannot be moved.
<img width="154" alt="outpointmarker" src="https://user-images.githubusercontent.com/12480900/69187706-6da87300-0b1b-11ea-9379-a2bbdd1ab593.png">

2019.46.6.1 with VLC player

**Comment by NateMccomb** [comment]
Fixed this in 2019.52.0.0, Let me know if it works better for you now.

**Comment by Kumasasa** [comment]
Yeah, that's working now.
