### ISSUE TITLE
"Copy TeslaCam viewer " (after formatting) copies TeslaCam Viewer but also subfolders

### ISSUE THREAD

**Issue by Kumasasa** [NateMccomb/TeslaCamViewerII#14]
Repro steps

* have a folder on your hard disk with TeslaCam Viewer  and a subfolder _Archive_ with archived clips
* Format a new drive by right clicking on the drive
* Answer "yes" to "Do you want to copy TeslaCam Viewer to the drive"
* Get freshly formatted drive with already 24 gigs of clips on it

<img width="796" alt="subfolders" src="https://user-images.githubusercontent.com/12480900/73973591-23b57900-4923-11ea-8c35-911300a5e9ce.png">
<img width="633" alt="new-drive" src="https://user-images.githubusercontent.com/12480900/73973847-a63e3880-4923-11ea-810b-3effd050fb45.png">

**Comment by NateMccomb** [comment]
I'll have to update the code so that the individual files needed are transferred and not the whole directory. I didn't expect other files or folders would be placed in the same directory as TeslaCam Viewer. I'll get this addressed in the next release.

**Comment by NateMccomb** [comment]
@Kumasasa this should be fixed in 2020.11.0.0 now
