### ISSUE TITLE
Camera Layout

### ISSUE THREAD

**Issue by natrlhy** [NateMccomb/TeslaCamViewerII#15]
Hi,

If I wanted to only export the Front/Left/Rear cameras I'm not seeing a way to create a new Camera Layout for these 3 cameras (right camera didn't have any meaningful video to include in an export). Is the ability to create your own Layouts there today?

**Comment by NateMccomb** [comment]
Here are two options for you. I have created and exported the views you are looking for. If you click on the Gear icon (Application settings) and select Layouts -> Import Layout, you can then select "Layout Config.TeslaCam" after unzipping the attached [Layout Config.zip](https://github.com/NateMccomb/TeslaCamViewerII/files/4202541/Layout.Config.zip)

Option 2:
You can click the "+" sign next to the layouts to create a new layout. Each camera is has a default aspect ratio of 4:3 (4 in width & 3 in height) so for 3 cameras wide you would want 12:3. You can then use the left mouse to drag each player to where you want them. There is a bug with VLC requiring you to manually select a time within "Selected Event" in order for the player windows to be enabled to move. (I'm still working to figure out what's causing this bug.)

**Comment by natrlhy** [comment]
Got it! Thanks!
