### ISSUE TITLE
Request: Option for ascending order of files.

### ISSUE THREAD

**Issue by Veadro** [NateMccomb/TeslaCamViewerII#6]
I'd like the ability to watch from start to finish.

**Comment by NateMccomb** [comment]
Technically you can start at the beginning of an event by either scrolling the main timeline bar all the way to the left or under Selected Event, scroll and select the bottom Time within the list. Most users are interested in Sentry Mode triggered event within the SentryClips folder so TeslaCam Viewer automatically starts playing every event at the time that Sentry Mode would have been triggered. 

An option could be added to the Application Settings that would override the Sentry Mode feature and automatically start every event from the beginning if you would like.

**Comment by Veadro** [comment]
My bad, I realized later that starting at the bottom does play in chronical order.
